title: Programmation VBA
description: L3 Management/ Comptabilité Contrôle Finances/ Economie de la Firme
markdown: kramdown
theme: jekyll-theme-cayman
footer_content: "© 2023 - Rohan Fossé"
logo_url: ./vba.ico

kramdown:
  parse_block_html: true
  parse_span_html: true
  toc_levels: 2..3
github:
  is_project_page: false